### ISSUE TITLE
command 'vscode-project-manager.addProject' not found

### ISSUE THREAD

**Issue by hihahihahoho** [WireCore/VS-Code-Project-Manager#2]
command 'vscode-project-manager.addCategory' not found

when i click the add project/add category button

**Comment by wiifree** [comment]
thanks for your information. i will look soon to solve that problem.

**Comment by gkavboy** [comment]
+1

**Comment by wiifree** [comment]
@hihahihahoho 
I currently update the extension to version 1.0.2. So you can update the extesion and let me know if its now fixed.
